version: "3"

services:
  redis:
    image: redis:7
  web:
    build: .
    # volumes:
    #   - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    # links:
    #   - db
    #   - redis
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
      DB_HOST: db
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

    volumes:
      - postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
volumes:
  postgresql:
